;;; aero-glass-effects.el --- Runtime effects engine for Aero Glass -*- lexical-binding: t -*-

;; Author: Keshav Italia
;; Version: 1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: faces themes

;;; Commentary:

;; Runtime effects companion to aero-glass-theme: picom compositor config,
;; custom fringe bitmaps, Vista-style mode-line, posframe glass parameters,
;; pulse-on-save shimmer, and EXWM float glass borders.
;;
;; Usage:
;;   (aero-glass-activate)        ; load theme + frame params
;;   (aero-glass-enable-effects)  ; enable runtime effects

;;; Code:

(require 'cl-lib)
(require 'pulse)

;; ── Group ─────────────────────────────────────────────────────────────────

(defgroup aero-glass nil
  "Aero Glass runtime effects."
  :group 'faces
  :prefix "aero-glass-")

;; ── Picom config ──────────────────────────────────────────────────────────

(defconst aero-glass-picom-config
  "# Aero Glass — picom compositor configuration
# ─────────────────────────────────────────────────────────────────────────
# Generated by aero-glass-effects.el for EXWM + Emacs aero-glass-theme
#
# Requires: picom-git (for dual_kawase blur + animations)
# Arch:     yay -S picom-git
# Debian:   build from https://github.com/jonaburg/picom
#
# Apply:    picom --config ~/.config/picom/picom.conf --daemon
# ─────────────────────────────────────────────────────────────────────────

backend = \"glx\";
glx-no-stencil = true;
vsync = true;
mark-wmwin-focused = true;
use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
unredir-if-possible = false;

# ── Frosted glass blur ────────────────────────────────────────────────────
blur-method = \"dual_kawase\";
blur-strength = 9;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = false;
blur-kern = \"3x3box\";
blur-background-exclude = [
  \"class_g = 'slop'\",
  \"class_g = 'maim'\",
  \"class_g = 'xdotool'\",
  \"class_g = 'xdpyinfo'\",
  \"name = 'cpt_frame_xcb_window'\",
  \"_GTK_FRAME_EXTENTS@:c\"
];

# ── Rounded corners ───────────────────────────────────────────────────────
corner-radius = 12;
round-borders = 1;
rounded-corners-exclude = [
  \"window_type = 'dock'\",
  \"window_type = 'desktop'\",
  \"class_g = 'slop'\"
];

# ── Shadows ───────────────────────────────────────────────────────────────
shadow = true;
shadow-radius = 28;
shadow-offset-x = -28;
shadow-offset-y = -14;
shadow-opacity = 0.75;
shadow-color = \"#000818\";
shadow-exclude = [
  \"class_g = 'slop'\",
  \"class_g = 'maim'\",
  \"name = 'Notification'\",
  \"class_g = 'Conky'\",
  \"class_g = 'Trayer'\",
  \"_GTK_FRAME_EXTENTS@:c\",
  \"window_type = 'desktop'\"
];

# ── Per-window opacity ────────────────────────────────────────────────────
# Emacs: 92% focused, 78% unfocused — the compositor does the rest
inactive-opacity = 0.85;
active-opacity = 1.0;
frame-opacity = 0.92;
inactive-opacity-override = false;
opacity-rule = [
  \"92:class_g = 'Emacs' && focused\",
  \"78:class_g = 'Emacs' && !focused\",
  \"96:class_g = 'kitty' && focused\",
  \"82:class_g = 'kitty' && !focused\"
];

# ── Fading ────────────────────────────────────────────────────────────────
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 8;
fade-exclude = [
  \"class_g = 'slop'\",
  \"class_g = 'maim'\"
];

# ── Animations (jonaburg/picom or pijulius fork required) ─────────────────
# Uncomment if your picom supports the animations module:
# animations = true;
# animation-stiffness = 280;
# animation-dampening = 30;
# animation-clamping = true;
# animation-mass = 1;
# animation-for-open-window = \"zoom\";
# animation-for-unmap-window = \"slide-down\";
# animation-for-transient-window = \"slide-down\";
# animation-for-workspace-switch-in = \"slide-left\";
# animation-for-workspace-switch-out = \"slide-right\";
"
  "Optimal picom configuration for Aero Glass compositor effects.
Paste into ~/.config/picom/picom.conf or use `aero-glass-write-picom-config'.")

(defcustom aero-glass-picom-config-path
  (expand-file-name "~/.config/picom/picom.conf")
  "Destination path for the generated picom configuration file."
  :type 'file
  :group 'aero-glass)

;;;###autoload
(defun aero-glass-write-picom-config (&optional restart)
  "Write `aero-glass-picom-config' to `aero-glass-picom-config-path'.
With prefix arg RESTART, kill any running picom and restart it."
  (interactive "P")
  (make-directory (file-name-directory aero-glass-picom-config-path) t)
  (write-region aero-glass-picom-config nil aero-glass-picom-config-path)
  (message "picom config written → %s" aero-glass-picom-config-path)
  (when restart
    (call-process-shell-command "pkill -x picom; sleep 0.4; picom --daemon" nil 0)
    (message "picom restarted with Aero Glass settings")))

;; ── Custom fringe bitmaps ─────────────────────────────────────────────────
;;
;; Each vector element = one pixel row, MSB = leftmost pixel (8px fringe).
;;
;;  aero-glass-diamond:   filled diamond    ....X...
;;                                          ...XXX..
;;                                          ..XXXXX.
;;                                          .XXXXXXX
;;                                          ..XXXXX.
;;                                          ...XXX..
;;                                          ....X...
;;
;;  aero-glass-chevron:   glass ">" arrow   ...XX...
;;                                          ..XXXX..
;;                                          .XXXXXX.
;;                                          XXXXXXXX
;;                                          .XXXXXX.
;;                                          ..XXXX..
;;                                          ...XX...
;;
;;  aero-glass-bar:       diff stripe       XXX.....  (3px, left-aligned)

(defun aero-glass--define-fringe-bitmaps ()
  "Install custom fringe bitmaps for Aero Glass."
  ;; Diamond — used for current-line and error indicators
  (define-fringe-bitmap 'aero-glass-diamond
    (vector #x08 #x1C #x3E #x7F #x3E #x1C #x08 #x00)
    nil nil 'center)
  ;; Chevron — used for warning / navigation indicators
  (define-fringe-bitmap 'aero-glass-chevron
    (vector #x18 #x3C #x7E #xFF #x7E #x3C #x18 #x00)
    nil nil 'center)
  ;; Thin bar — used for diff add/change/delete stripes
  (define-fringe-bitmap 'aero-glass-bar
    (vector #xE0 #xE0 #xE0 #xE0 #xE0 #xE0 #xE0 #xE0)
    nil nil 'center)
  ;; Circle — used for info indicators
  (define-fringe-bitmap 'aero-glass-circle
    (vector #x3C #x7E #xFF #xFF #xFF #x7E #x3C #x00)
    nil nil 'center)
  ;; Wire up diff-hl if loaded
  (when (boundp 'diff-hl-fringe-bitmaps)
    (setq diff-hl-fringe-bitmaps
          '((add . aero-glass-bar)
            (delete . aero-glass-bar)
            (change . aero-glass-bar)))
    (setq diff-hl-fringe-side 'left))
  ;; Wire up flycheck if loaded
  (when (featurep 'flycheck)
    (flycheck-redefine-standard-error-levels
     'left-fringe
     'aero-glass-diamond
     'aero-glass-chevron
     'aero-glass-circle))
  ;; Buffer boundaries — glass chevrons
  (setq-default indicate-buffer-boundaries
                '((top . left) (bottom . left) (t . right)))
  (setq fringe-indicator-alist
        (cons '(continuation aero-glass-chevron aero-glass-chevron)
              (assq-delete-all 'continuation fringe-indicator-alist))))

;; ── Posframe glass ────────────────────────────────────────────────────────

(defun aero-glass--configure-posframes ()
  "Apply glass alpha + border width to all posframe consumers."
  ;; vertico-posframe
  (setq vertico-posframe-parameters
        '((alpha-background . 88)
          (alpha . 100)
          (internal-border-width . 2)))
  ;; which-key-posframe
  (setq which-key-posframe-parameters
        '((alpha-background . 88)
          (alpha . 100)
          (internal-border-width . 2)))
  ;; corfu popup tweaks
  (setq-default corfu-count 14
                corfu-min-width 55
                corfu-max-width 90
                corfu-auto-delay 0.15
                corfu-popupinfo-delay '(0.4 . 0.1)))

;; ── Vista-style mode-line ─────────────────────────────────────────────────
;;
;; Layout:
;;   [◈WS] buffer-name ● │ Mode  ──────────  ⎇ branch │ L:C │ HH:MM
;;
;; Uses faces defined in aero-glass-theme.el (aero-glass-ml-*).

(defun aero-glass--ml-sep ()
  (propertize " │ " 'face 'aero-glass-ml-sep))

(defun aero-glass--ml-ws-segment ()
  "Workspace number, only in EXWM."
  (when (bound-and-true-p exwm-workspace-current-index)
    (propertize (format " ◈%d " exwm-workspace-current-index)
                'face 'aero-glass-ml-workspace
                'help-echo (format "EXWM workspace %d" exwm-workspace-current-index))))

(defun aero-glass--ml-buf-segment ()
  "Buffer name with glass status dot."
  (let* ((name (buffer-name))
         (trunc (truncate-string-to-width name 48 nil nil "…"))
         (indicator
          (cond (buffer-read-only
                 (propertize " ■" 'face 'aero-glass-ml-readonly
                             'help-echo "Read-only"))
                ((buffer-modified-p)
                 (propertize " ●" 'face 'aero-glass-ml-modified
                             'help-echo "Modified"))
                (t ""))))
    (concat (propertize trunc 'face 'aero-glass-ml-buffer) indicator)))

(defun aero-glass--ml-mode-segment ()
  "Major mode, abbreviated."
  (propertize (string-trim (format-mode-line mode-name))
              'face 'aero-glass-ml-mode))

(defun aero-glass--ml-vc-segment ()
  "VC branch with ⎇ glyph."
  (when (and (bound-and-true-p vc-mode) vc-mode)
    (propertize
     (concat "⎇ "
             (string-trim (replace-regexp-in-string "^ ?Git[:-]?" "" vc-mode)))
     'face 'aero-glass-ml-vc
     'help-echo "Current branch")))

(defun aero-glass--ml-lsp-segment ()
  "LSP active indicator."
  (cond
   ((and (fboundp 'eglot-managed-p) (eglot-managed-p))
    (propertize "⬡ LSP" 'face 'aero-glass-ml-lsp 'help-echo "Eglot active"))
   ((bound-and-true-p lsp-mode)
    (propertize "⬡ LSP" 'face 'aero-glass-ml-lsp 'help-echo "lsp-mode active"))
   (t nil)))

(defun aero-glass--ml-pos-segment ()
  "Line:column position."
  (propertize (format "%d:%d" (line-number-at-pos) (current-column))
              'face 'aero-glass-ml-position))

(defun aero-glass--ml-time-segment ()
  "Current time HH:MM."
  (propertize (format-time-string "%H:%M") 'face 'aero-glass-ml-time))

(defun aero-glass--ml-right ()
  "Assemble the right side of the mode-line as a plain string."
  (let* ((sep  (aero-glass--ml-sep))
         (vc   (aero-glass--ml-vc-segment))
         (lsp  (aero-glass--ml-lsp-segment))
         (pos  (aero-glass--ml-pos-segment))
         (time (aero-glass--ml-time-segment))
         (left-parts (delq nil (list vc (when lsp (concat sep lsp))))))
    (concat
     (when left-parts (concat (mapconcat #'identity left-parts "") sep))
     pos sep time " ")))

(defun aero-glass--ml-filler ()
  "Space + right content, right-aligned to window edge."
  (let* ((right (aero-glass--ml-right))
         (width (string-width (substring-no-properties right))))
    (concat
     (propertize " " 'display `(space :align-to (- right ,width)))
     right)))

(defvar aero-glass-modeline-format
  '("%e"
    (:eval (or (aero-glass--ml-ws-segment) ""))
    " "
    (:eval (aero-glass--ml-buf-segment))
    (:eval (aero-glass--ml-sep))
    (:eval (aero-glass--ml-mode-segment))
    (:eval (aero-glass--ml-filler)))
  "Aero Glass Vista-style mode-line format.")

;;;###autoload
(defun aero-glass-enable-modeline ()
  "Install the Aero Glass Vista-style mode-line globally."
  (interactive)
  (setq-default mode-line-format aero-glass-modeline-format))

;;;###autoload
(defun aero-glass-disable-modeline ()
  "Restore the default Emacs mode-line format."
  (interactive)
  (kill-local-variable 'mode-line-format)
  (setq-default mode-line-format (default-value 'mode-line-format)))

;; ── Pulse shimmer effects ─────────────────────────────────────────────────

;;;###autoload
(defun aero-glass-pulse-line ()
  "Flash the current line with an Aero Glass glass shimmer."
  (interactive)
  (let ((pulse-delay 0.05)
        (pulse-iterations 10))
    (pulse-momentary-highlight-one-line (point) 'aero-glass-pulse)))

(defun aero-glass--pulse-on-save ()
  (when (buffer-file-name)
    (aero-glass-pulse-line)))

(defun aero-glass--setup-pulse-hooks ()
  (add-hook 'after-save-hook #'aero-glass--pulse-on-save))

(defun aero-glass--teardown-pulse-hooks ()
  (remove-hook 'after-save-hook #'aero-glass--pulse-on-save))

;; ── EXWM float glass borders ─────────────────────────────────────────────

(defun aero-glass--configure-exwm-float ()
  "Style exwm-float borders with Aero Glass colours."
  (when (boundp 'exwm-float-border)
    ;; stationary: deep glass edge; moving: bright ice-blue glow
    (setq exwm-float-border
          '(:stationary ("#1a2d5c" . 2) :moving ("#64b5f6" . 3)))))

;; ── Doom-modeline tuning ──────────────────────────────────────────────────

(defun aero-glass--configure-doom-modeline ()
  "Tune doom-modeline to show more information with glass aesthetics."
  (when (fboundp 'doom-modeline-mode)
    (setq doom-modeline-height 30
          doom-modeline-bar-width 5
          doom-modeline-window-width-limit 0.30
          doom-modeline-project-detection 'auto
          doom-modeline-buffer-file-name-style 'truncate-upto-project
          doom-modeline-icon t
          doom-modeline-major-mode-icon t
          doom-modeline-major-mode-color-icon t
          doom-modeline-buffer-modification-icon t
          doom-modeline-unicode-fallback nil
          doom-modeline-enable-word-count nil
          doom-modeline-time t
          doom-modeline-battery t
          doom-modeline-persp-name t
          doom-modeline-persp-icon t)))

;; ── Frame parameters ──────────────────────────────────────────────────────

(defun aero-glass--configure-frame ()
  "Apply Aero Glass window geometry parameters."
  (dolist (p '((internal-border-width . 10)
               (right-divider-width   . 2)
               (bottom-divider-width  . 2)))
    (set-frame-parameter nil (car p) (cdr p))
    (add-to-list 'default-frame-alist p)))

;; ── Flycheck bitmap helper ────────────────────────────────────────────────
;; flycheck-redefine-standard-error-levels does not exist; use direct setq.

(defun aero-glass--configure-flycheck-bitmaps ()
  "Apply custom bitmaps to flycheck fringe indicators."
  (when (featurep 'flycheck)
    (setq flycheck-indication-mode 'left-fringe)
    (setq flycheck-error-symbol   'aero-glass-diamond
          flycheck-warning-symbol 'aero-glass-chevron
          flycheck-info-symbol    'aero-glass-circle)))

;; ── Customisation flags ───────────────────────────────────────────────────

(defcustom aero-glass-effects-modeline nil
  "When non-nil, `aero-glass-enable-effects' replaces doom-modeline with the
Aero Glass Vista-style mode-line.  Defaults to nil so doom-modeline is kept."
  :type 'boolean
  :group 'aero-glass)

(defcustom aero-glass-effects-fringe-bitmaps t
  "When non-nil, install custom Aero Glass fringe bitmaps."
  :type 'boolean
  :group 'aero-glass)

(defcustom aero-glass-effects-posframe-glass t
  "When non-nil, configure posframe transparency for glass look."
  :type 'boolean
  :group 'aero-glass)

(defcustom aero-glass-effects-pulse t
  "When non-nil, install pulse-on-save shimmer hook."
  :type 'boolean
  :group 'aero-glass)

;; ── Main entry point ──────────────────────────────────────────────────────

;;;###autoload
(defun aero-glass-enable-effects ()
  "Enable all Aero Glass runtime effects.

Activates fringe bitmaps, posframe glass, doom-modeline tuning,
pulse-on-save shimmer, and EXWM float borders.  Optionally installs
the Vista-style mode-line if `aero-glass-effects-modeline' is non-nil.

Recommended usage:
  (aero-glass-activate)       ; in k-themes.el / init.el
  (aero-glass-enable-effects)"
  (interactive)
  (aero-glass--configure-frame)
  (when aero-glass-effects-fringe-bitmaps
    (aero-glass--define-fringe-bitmaps)
    (aero-glass--configure-flycheck-bitmaps))
  (when aero-glass-effects-posframe-glass
    (aero-glass--configure-posframes))
  (aero-glass--configure-doom-modeline)
  (when aero-glass-effects-modeline
    (aero-glass-enable-modeline))
  (when aero-glass-effects-pulse
    (aero-glass--setup-pulse-hooks))
  (aero-glass--configure-exwm-float)
  (message "Aero Glass effects enabled"))

(provide 'aero-glass-effects)

;;; aero-glass-effects.el ends here
