name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.el'
      - '**/*.org'

jobs:
  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 30.1

    steps:
      - name: Cache ELPA packages
        uses: actions/cache@v3
        with:
          path: ~/.emacs.d/elpa
          key: ${{ runner.os }}-emacs-${{ matrix.emacs-version }}-elpa
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Validate Configuration
        run: |
          emacs --batch --eval "
          (setq debug-on-error t)
          (setq user-emacs-directory \"$HOME/.emacs.d\")
          (load-file \"$HOME/.emacs.d/init.el\")"
